### ISSUE TITLE
Use localStorage to remember scores set

### ISSUE THREAD

**Issue by joelmarquez90** [lsv/fifa-worldcup-2018-jsfrontend#2]
It would be great to use the localStorage so the user can fully complete its predictions and then, when loading the site again, remember them. I can submit a PR with that, I'm kind of new with Vue but if you help me we can add that together.

**Comment by JoeyHa** [comment]
I think thats a great idea , i used your project just for understanding
NodeJS  , Hope i will be able to be more helpful in the nearest future.

In my opinion you should use a DB to store the result of each User , maybe
you should add a login options and than save the result of each user in a
DB schema .

tell me what do you think about that

**Comment by lsv** [comment]
That would be great.
To make it its "just" by "hooking" into the mutations in [data.ts](https://github.com/lsv/fifa-worldcup-2018-jsfrontend/blob/master/src/store/modules/data.ts)

I havent had time to update this frontend - there are more updates, like penalty in knockout matches.

**Comment by zhengfen** [comment]
Many thanks !!!!   
I learned vuex and typescript thanks to your project.  I added backend for user pronostics
https://foot.zhengfen.ch/

**Comment by ondapc** [comment]
Any chance to incorporate this would be very cool indeed --- lsv. 

Any chance to make this public - zhengfen?

**Comment by zhengfen** [comment]
I used laravel for the backend, might however not be the best solution. Here you can check out the modifications for the frontend: 
https://github.com/zhengfen/worldcup2018/tree/master/resources/assets/js
