### ISSUE TITLE
only allow numbers 0-9 to be input into the form inputs

### ISSUE THREAD

**Issue by ondapc** [lsv/fifa-worldcup-2018-jsfrontend#3]
Hello, how about a little javascript that will only allow the usage of numbers...

If you prefer to use html5 that might be a way to go aswell...
<input type="number" min="0" step="1"/>

**Comment by lsv** [comment]
As this was just a fast demo, so I could test my json file, I would recommend to fork this and build your own, or overwrite stuff.

See fx #2
