### ISSUE TITLE
How to run this project on website?

### ISSUE THREAD

**Issue by onepelaez** [lsv/fifa-worldcup-2018-jsfrontend#4]
Hi
I've cloned this project and run `npm install` successfully 
Now I'm trying to run this project but I can't figure it out 

Any help? Please
Regards

**Comment by FilhoSergio** [comment]
up

**Comment by lsv** [comment]
First install dependencies with `npm install` then either build or serve

`npm run build` now you will have a index.html file in the dist folder - upload this to your server and open your URL.

Or, you can run `npm run serve` and you can open it with `http://localhost:3000` (cant remember which port, but the url are written in the terminal)

**Comment by FilhoSergio** [comment]
Nice bro.
